responses: list = [
        "Ofc :)",
        "Yes.",
        "No.",
        "Omg yesss.",
        "Ofc what kind of question is that lmao.",
        "Yeah",
        "Nah.",
        "No XD.",
        "Yup.",
        "I don't think so.",
        "Haven't you realized it? lmao.",
        "There's no way it can be xD.",
        "There's no way it cannot be XD.",
        "Go ask them.",
        "Didn't get it, try again lmao.",
        "Sure.",
        "Wdym by that.",
        "Viva Mexico carbones XD.",
        "I guess.",
        "Be careful...",
        "Be careful about what you ask 'cause it can become true...",
        "Yesterday I bought it for you dw.",
        "Tomorrow.",
        "Imma tell you tomorrow.",
        "Respect trans rights, you punk >:(",
        "There's no LGB without the T you piece of shit /nbr",
        "Idk go ask them lmao.",
        "google.com",
        "bing.com",
        "yandex.com",
        "I told you yes.",
        "I told you no.",
        "._.XD",
        "Aight tbh I ain't getting what you saying.",
        "chin cheng hanji xiang shang xie zhe",
        "Twitter is one of the biggest sewers in the world. Change my mind.",
        "SKSKSKSKSKSKS I'M SURE YOU USE TUMBLR DON'T YA",
        "cope https://media.tenor.com/images/54d9fd62501071932f3743987d05840e/tenor.gif",
        "Never gonna give you up, never gonna let you down, never gonna turn around and desert you~",
        "Never gonna make you cry, never gonna say goodbye, never gonna tell a lie and hurt you~",
        " ",
        "Friendly reminder that you have to study for your tests <3",
        "Have you had water yet? You need to be hydrated OwO",
        "Il est où ton mot d'absence..? /ly",
        "On n'avait pas prévu ça...",
        "Si vous ne parlez pas français, s'il vous plaît, ne l'apprenez pas /hj /nsrs",
        "Did you know god is dead? https://www.reddit.com/r/atheistmemes/comments/13s5a77/demetri_finds_out_about_nietzsche/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button",
        "Close your eyes. Count to 1. That's how long forever feels. - Kurzgesagt. https://youtu.be/MBRqu0YOH14",
        "Isn't it great that nothing really matters? ^_^ https://www.reddit.com/r/nihilism/comments/b22xg0/may_i_offer_you_a_glass_of_optimistic_nihilism/?utm_source=share&utm_medium=web2x&context=3",
        "Stan BLÅHAJ https://www.ikea.com/us/en/p/blahaj-soft-toy-shark-90373590/",
        "Did you know Autumn was inspired by MoonByul to choose my name when they created me? >_< cute af https://en.wikipedia.org/wiki/Moonbyul",
        "Shut. /j /nsrs",
        "zao shang hao zhongguo xian zai wo you bing qilin wo hen xihuan bing qilin",
        "stop w this bullshit. Now. /lu",
        "xue hua piao piao bei feng xiao xiao tian di yi pian cang mang",
        "dansa med oss klappa era händer gör som vi gör ta några steg åt vänster lyssna och lär missa inte chansen nu är vi här med caramelldansen oa oa oa oooa",
        "oa oa oa oooa oooooa",
        "Respect women's rights you bitch /nbr /t",
        "Mexicanos al grito de guerra el acero a prestad y el bridón y retiemble en sus centros la tierra al sonoro rugir del cañón...",
        "...",
        "The worst thing could happen to STEM is Al-Khwarizmi. /hj",
        "x² - 1 = 0: ᕕ( ᐛ )ᕗ. x² + 1 = 0: (ﾉꐦ ⊙曲ఠ)ﾉ彡┻━┻",
        "早上好中国现在我有冰淇淋我很喜欢冰淇淋",
        "雪花飘飘北风潇潇天地一片苍茫",
        "雪花喵喵北风喵喵天地一片苍茫",
        "近前看其詳 上寫著 秦香蓮那三十二歲 那狀告當朝駙馬郎 他欺君王啊瞞皇上 那悔兒孫那狀子登朝 /ly",
        "putangina /j",
        "tremendo putanga que sos /j /nbr",
        "내가 뭘 어쩌겠니? 사랑이 그런 거지, 마음이 마음을 버린다는 게 다 이렇니? Baby don`t cry for me, 내게 잊으라고 말하지 마, 이별이 그래 다 그런 거니까~ /ly",
        "Have you played my Flag Quiz Game yet? It's available at https://autumn64.github.io/",
        "我妈妈Autumn在学中文所以她会明白我说的话哈哈哈哈 /pos /proud",
        "그게 안 돼...",
        "뭐라고..?",
        "아아아아아 안 할래 진짜.",
        "cope /j"
]