responses = [
"Ofc :)",
"Yes.",
"No.",
"Omg yesss.",
"Ofc what kind of question is that lmao.",
"Yeah",
"Nah.",
"No XD.",
"Yup.",
"I don't think so.",
"Haven't you realized it? lmao.",
"There's no way it can be xD.",
"There's no way it cannot be XD.",
"Go ask them.",
"Didn't get it, try again lmao.",
"Sure.",
"Wdym by that.",
"Ew are you wahhabist.",
"Viva Mexico carbones XD.",
"I guess.",
"Halal.",
"Haraam.",
"Be careful...",
"Be careful about what you ask 'cause it can become true...",
"Yesterday I bought it for you dw.",
"Tomorrow.",
"Imma tell you tomorrow.",
"Idk go ask them lmao.",
"google.com",
"bing.com",
"yandex.com",
"I told you yes.",
"I told you no.",
"Lemme ask Assim al Hakeem lmfao.",
"._.XD",
"zao shang hao zhongguo xian zai wo you bing qilin wo hen xihuan bing qilin",
"xue hua piao piao bei feng xiao xiao tian di yi pian cang mang",
"Pakistan Zindabad.",
"Die Erdoğan.",
"Nooooooooo no debiste pasar por Ecatepec, ahora estás en una bolsa en un río de Chihuahua.",
"Nooooooooo no debiste pasar por Sinaloa, ahora estás sin cabeza en un cerro.",
"Mexicanos al grito de guerra el acero a prestad y el bridón y retiemble en sus centros la tierra al sonoro rujir del cañón...",
"...",
"No te vayas a meter a Ecatepec, te van a meter a una bolsa y te van a dejar en un río de Chihuahua.",
"The worst thing could happen to STEM is Al-Khwarizmi. /hj",
"早上好中国现在我有冰淇淋我很喜欢冰淇淋",
"雪花飘飘北风潇潇天地一片苍茫",
"雪花喵喵北风喵喵天地一片苍茫",
"puntangina /j",
"내가 뭘 어쩌겠니? 사랑이 그런 거지, 마음이 마음을 버린다는 게 다 이렇니? Baby don`t cry for me, 내게 잊으라고 말하지 마, 이별이 그래 다 그런 거니까~"
]