LANGUAGES: dict = {
    'af': 'Afrikaans',
    'sq': 'Albanian',
    'am': 'Amharic',
    'ar': 'Arabic',
    'hy': 'Armenian',
    'az': 'Azerbaijani',
    'eu': 'Basque',
    'be': 'Belarusian',
    'bn': 'Bengali',
    'bs': 'Bosnian',
    'bg': 'Bulgarian',
    'ca': 'Catalan',
    'ceb': 'Cebuano',
    'ny': 'Chichewa',
    'zh-cn': 'Chinese (simplified)',
    'zh-tw': 'Chinese (traditional)',
    'zh-CN': 'Chinese (simplified)',
    'zh-TW': 'Chinese (traditional)',
    'co': 'Corsican',
    'hr': 'Croatian',
    'cs': 'Czech',
    'da': 'Danish',
    'nl': 'Dutch',
    'en': 'English',
    'eo': 'Esperanto',
    'et': 'Estonian',
    'tl': 'Filipino',
    'fi': 'Finnish',
    'fr': 'French',
    'fy': 'Frisian',
    'gl': 'Galician',
    'ka': 'Georgian',
    'de': 'German',
    'el': 'Greek',
    'gu': 'Gujarati',
    'ht': 'Haitian creole',
    'ha': 'Hausa',
    'haw': 'Hawaiian',
    'iw': 'Hebrew',
    'he': 'Hebrew',
    'hi': 'Hindi',
    'hmn': 'Hmong',
    'hu': 'Hungarian',
    'is': 'Icelandic',
    'ig': 'Igbo',
    'id': 'Indonesian',
    'ga': 'Irish',
    'it': 'Italian',
    'ja': 'Japanese',
    'jw': 'Javanese',
    'kn': 'Kannada',
    'kk': 'Kazakh',
    'km': 'Khmer',
    'ko': 'Korean',
    'ku': 'Kurdish (kurmanji)',
    'ky': 'Kyrgyz',
    'lo': 'Lao',
    'la': 'Latin',
    'lv': 'Latvian',
    'lt': 'Lithuanian',
    'lb': 'Luxembourgish',
    'mk': 'Macedonian',
    'mg': 'Malagasy',
    'ms': 'Malay',
    'ml': 'Malayalam',
    'mt': 'Maltese',
    'mi': 'Maori',
    'mr': 'Marathi',
    'mn': 'Mongolian',
    'my': 'Myanmar (burmese)',
    'ne': 'Nepali',
    'no': 'Norwegian',
    'or': 'Odia',
    'ps': 'Pashto',
    'fa': 'Persian',
    'pl': 'Polish',
    'pt': 'Portuguese',
    'pa': 'Punjabi',
    'ro': 'Romanian',
    'ru': 'Russian',
    'sm': 'Samoan',
    'gd': 'Scots gaelic',
    'sr': 'Serbian',
    'st': 'Sesotho',
    'sn': 'Shona',
    'sd': 'Sindhi',
    'si': 'Sinhala',
    'sk': 'Slovak',
    'sl': 'Slovenian',
    'so': 'Somali',
    'es': 'Spanish',
    'su': 'Sundanese',
    'sw': 'Swahili',
    'sv': 'Swedish',
    'tg': 'Tajik',
    'ta': 'Tamil',
    'te': 'Telugu',
    'th': 'Thai',
    'tr': 'Turkish',
    'uk': 'Ukrainian',
    'ur': 'Urdu',
    'ug': 'Uyghur',
    'uz': 'Uzbek',
    'vi': 'Vietnamese',
    'cy': 'Welsh',
    'xh': 'Xhosa',
    'yi': 'Yiddish',
    'yo': 'Yoruba',
    'zu': 'Zulu'
    }

LANGUAGESSP: dict = {
    'af': 'Afrikaans',
    'sq': 'Albanés',
    'am': 'Amhárico',
    'ar': 'Árabe',
    'hy': 'Armenio',
    'az': 'Azerí',
    'eu': 'Vasco',
    'be': 'Bielorruso',
    'bn': 'Bengalí',
    'bs': 'Bosnio',
    'bg': 'Búlgaro',
    'ca': 'Catalán',
    'ceb': 'Cebuano',
    'ny': 'Chichewa',
    'zh-cn': 'Chino (simplificado)',
    'zh-tw': 'Chino (tradicional)',
    'zh-CN': 'Chino (simplificado)',
    'zh-TW': 'Chino (tradicional)',
    'co': 'Corso',
    'hr': 'Croata',
    'cs': 'Checo',
    'da': 'Danés',
    'nl': 'Neerlandés',
    'en': 'Inglés',
    'eo': 'Esperanto',
    'et': 'Estonio',
    'tl': 'Filipino',
    'fi': 'Finlandés',
    'fr': 'Francés',
    'fy': 'Frisio',
    'gl': 'Gallego',
    'ka': 'Georgiano',
    'de': 'Alemán',
    'el': 'Griego',
    'gu': 'Gujarati',
    'ht': 'Criollo haitiano',
    'ha': 'Hausa',
    'haw': 'Hawaiano',
    'iw': 'Hebreo',
    'he': 'Hebreo',
    'hi': 'Hindi',
    'hmn': 'Hmong',
    'hu': 'Húngaro',
    'is': 'Islandés',
    'ig': 'Igbo',
    'id': 'Indonesio',
    'ga': 'Irlandés',
    'it': 'Italiano',
    'ja': 'Japonés',
    'jw': 'Javanés',
    'kn': 'Canarés',
    'kk': 'Kazajo',
    'km': 'Khmer',
    'ko': 'Coreano',
    'ku': 'Kurdo',
    'ky': 'Kyrgyz',
    'lo': 'Lao',
    'la': 'Latín',
    'lv': 'Letón',
    'lt': 'Lituano',
    'lb': 'Luxemburgués',
    'mk': 'Macedonio',
    'mg': 'Malgache',
    'ms': 'Malayo',
    'ml': 'Malayalam',
    'mt': 'Maltés',
    'mi': 'Maori',
    'mr': 'Marathi',
    'mn': 'Mongol',
    'my': 'Myanmar',
    'ne': 'Nepalí',
    'no': 'Noruego',
    'or': 'Odia',
    'ps': 'Pashto',
    'fa': 'Persa',
    'pl': 'Polaco',
    'pt': 'Portugués',
    'pa': 'Punjabi',
    'ro': 'Rumano',
    'ru': 'Ruso',
    'sm': 'Samoan',
    'gd': 'Gaelico escocés',
    'sr': 'Serbio',
    'st': 'Sesotho',
    'sn': 'Shona',
    'sd': 'Sindhi',
    'si': 'Sinhala',
    'sk': 'Eslovaco',
    'sl': 'Eslovenio',
    'so': 'Somalí',
    'es': 'Español',
    'su': 'Sundanés',
    'sw': 'Swahili',
    'sv': 'Sueco',
    'tg': 'Tajiko',
    'ta': 'Tamil',
    'te': 'Telugu',
    'th': 'Tailandés',
    'tr': 'Turco',
    'uk': 'Ucraniano',
    'ur': 'Urdu',
    'ug': 'Uyghur',
    'uz': 'Uzbeko',
    'vi': 'Vietnamita',
    'cy': 'Welsh',
    'xh': 'Xhosa',
    'yi': 'Yiddish',
    'yo': 'Yoruba',
    'zu': 'Zulu'
    }

hugs: list = [
    "https://media.tenor.com/TQHYnWtxOOsAAAAi/hug.gif",
    "https://media.tenor.com/fFpVFqD_4esAAAAi/peluk.gif",
    "https://media.tenor.com/vnGjPkARnCsAAAAC/hug.gif",
    "https://media.tenor.com/qP73-I-x9aAAAAAC/care-hugs.gif",
    "https://media.tenor.com/DVS7HcEPYsAAAAAC/huggies.gif",
    "https://media.tenor.com/gMDaiGvsdZ0AAAAd/reencuentros-reencuentro.gif",
    "https://media.tenor.com/3MA0xSfEs1kAAAAC/pingu-robby-the-seal.gif",
    "https://media.tenor.com/QqeP0afq18sAAAAC/hug-mochi.gif",
    "https://media.tenor.com/sSbr1al2-KQAAAAC/so-cute.gif",
    "https://media.tenor.com/d5r9HPFy_PEAAAAd/walkergifs-hug.gif",
    "https://media.tenor.com/v7Ba8diy6qMAAAAC/hug.gif",
    "https://media.tenor.com/vYG78xkQXUQAAAAS/cat-cat-hug.gif",
    "https://media.tenor.com/oV7gjAbOQJEAAAAC/saf-ghost.gif",
    "https://media.tenor.com/WTnrWR01Ka8AAAAC/hug-hugs.gif",
    "https://media.tenor.com/Ml_tOetr-Q4AAAAS/ohmnamon-ohmnamon-hug.gif",
    "https://media.tenor.com/OKfGxyfc-b8AAAAd/cute-kiss.gif",
    "https://media.tenor.com/o-VNLfZI3VAAAAAd/cravity-cravity-allen.gif",
    "https://media.tenor.com/EqzscTWbbXEAAAAC/kanna-dragon-maid.gif",
    "https://media.tenor.com/yz_nVDTQ-TgAAAAd/monika-ddlc.gif",
    "https://media.tenor.com/RnEOvkzRMvoAAAAC/touhou-fumo.gif",
    "https://media.tenor.com/KAnmkpCaUxoAAAAC/drake-and.gif",
    "https://media.tenor.com/qztK7GiuiR4AAAAC/sushichaeng-blackpink.gif",
    "https://media.tenor.com/J4x-cfjuT0oAAAAd/the-owl-house-luz-noceda.gif",
    "https://media.tenor.com/LPY8UkZZdAAAAAAC/hugs-and.gif",
    "https://media.tenor.com/dJBtriYvXWoAAAAC/care-love.gif",
    "https://media.tenor.com/aacuNFvsDmEAAAAC/omori-omori-sunny.gif",
    "https://media.tenor.com/M87MdS6D7VoAAAAC/hugs-hugging.gif",
    "https://media.tenor.com/m1Ha7KTp4sQAAAAC/marshymello0407-mello-hug.gif",
    "https://media.tenor.com/oSPZDjEf9vQAAAAC/anime-hug-anime-hugging.gif",
    "https://media.tenor.com/z1fANNQdx2EAAAAd/cute-hug-anime-hug.gif",
    "https://media.tenor.com/QqeP0afq18sAAAAC/hug-mochi.gif"
]

cryings: list = [
    "https://media.tenor.com/dIR5p38-V4EAAAAi/cry-maddrey-maddrey.gif",
    "https://media.tenor.com/qzjLn_6vNhAAAAAi/capoo-bugcat.gif",
    "https://media.tenor.com/nz50SM3OwSsAAAAi/cat-peach.gif",
    "https://media.tenor.com/K61LBZu_g70AAAAd/cry-dog.gif",
    "https://media.tenor.com/5MfiBjR3F3gAAAAC/tears.gif",
    "https://media.tenor.com/ww6svxpx7koAAAAC/sadcat.gif",
    "https://media.tenor.com/UIXwsWt9n9cAAAAd/crying-girl-crying.gif",
    "https://media.tenor.com/NlLyjpr62VYAAAAd/sobbing-sob.gif",
    "https://media.tenor.com/PLX-tGVl7CQAAAAC/crying-cry.gif",
    "https://media.tenor.com/wtODXBplQHQAAAAd/cat-cry-gif-crying-cat-gif.gif",
    "https://media.tenor.com/1zjvBJY2k4QAAAAC/sad-cony.gif",
    "https://media.tenor.com/sDSVqF_GmXkAAAAC/%E0%B8%87%E0%B8%AD%E0%B8%99.gif",
    "https://media.tenor.com/htMd6zA1Ta8AAAAC/sad-crying.gif",
    "https://media.tenor.com/K2V8Zbx5ezgAAAAC/cute-so.gif",
    "https://media.tenor.com/8gKI4kiUHVYAAAAC/spongebob-crying.gif",
    "https://media.tenor.com/qrMXo5T5HZAAAAAC/cute-cry.gif",
    "https://media.tenor.com/fEBD4ux6_ncAAAAC/no-cry.gif",
    "https://media.tenor.com/qcHKzwCJAyEAAAAC/cry.gif",
    "https://media.tenor.com/0qj0aqZ0nucAAAAC/anya-spy-x-family-anime-anya-crying.gif",
    "https://media.tenor.com/LEZsSrDtUWoAAAAC/smile-precure-precure.gif",
    "https://media.tenor.com/wufP2FzJRikAAAAd/crying-cat.gif",
    "https://media.tenor.com/BcY77dUnhHwAAAAC/mobile-girl-mim-crying.gif",
    "https://media.tenor.com/K78CyS6Q68kAAAAd/uraraka-uraraka-ochako.gif",
    "https://media.tenor.com/or3eefVsI2gAAAAd/venti-genshin-impact-crying-venti.gif",
    "https://media.tenor.com/szFJZKSZrswAAAAd/pikachu-sad.gif",
    "https://media.tenor.com/YM74HxjzuJwAAAAC/spongebob-cry.gif",
    "https://media.tenor.com/rIapMID9RHIAAAAC/cry-cute.gif"
]

caramell: list = [
    "https://media.tenor.com/dCq1bVzStK8AAAAC/caramelldansen-dancing.gif",
    "https://media.tenor.com/uqDPV_vPq5kAAAAC/caramelldansen-dance.gif",
    "https://media.tenor.com/ltZGwM03N_AAAAAC/caramell-dansen-dance.gif",
    "https://media.tenor.com/3_8q31A0Z-kAAAAd/clop-caramel-dansen.gif",
    "https://media.tenor.com/Gi7HIQm6EdAAAAAC/caramelldansen-princess-daisy.gif",
    "https://media.tenor.com/jpMoE7uEz4wAAAAC/anime-dance.gif",
    "https://media.tenor.com/TgdzhJdl6w4AAAAd/caramelldansen-lucky-star.gif",
    "https://media.tenor.com/dHDAqTOEIgAAAAAC/sonic-shadow.gif",
    "https://media.tenor.com/r1bRaVV1VkwAAAAC/touhou-caramelldansen.gif",
    "https://media.tenor.com/35zPcaw0VpUAAAAC/ilulu-caramelldansen.gif",
    "https://media.tenor.com/T8YZ5vXZhFUAAAAC/shinobu-shinobu-kocho.gif"
]

lgbtqplus: list = [
    "https://i.pinimg.com/236x/59/c8/45/59c84507bd7c0f309cd6633baea1cd41.jpg",
    "https://i.pinimg.com/564x/48/61/87/48618744e08a918d442fea8f22137010.jpg",
    "https://i.pinimg.com/236x/2d/a6/eb/2da6eb75ad81f42bb6c9e10dec28787f.jpg",
    "https://i.pinimg.com/564x/62/99/8b/62998bbadd4ac989c810a84a2c25a135.jpg",
    "https://i.pinimg.com/564x/09/af/76/09af7647e182031b47b2095621628415.jpg",
    "https://i.pinimg.com/236x/56/2e/0a/562e0a9dfc50e1bb201d708069c4ab5d.jpg",
    "https://i.pinimg.com/564x/7e/3a/44/7e3a44321c983763990eb0a37861588c.jpg",
    "https://i.pinimg.com/564x/3d/13/2f/3d132f8d0673fe1800664ea48c939f7e.jpg",
    "https://i.pinimg.com/236x/26/99/55/269955b0f2b3b94cf70e2b6a3968c2c4.jpg",
    "https://i.pinimg.com/236x/ca/04/3b/ca043bfdbd0739b7d671d8688e25b767.jpg",
    "https://i.pinimg.com/564x/77/b9/1b/77b91b58e3387bdfd8ee161a197b83c1.jpg",
    "https://i.pinimg.com/564x/36/ea/1a/36ea1af35a9e822906c153114fe6ef29.jpg",
    "https://i.pinimg.com/564x/e0/45/b1/e045b1cdd39796655d80f2b40bb52cd2.jpg",
    "https://i.pinimg.com/236x/31/b5/3b/31b53bc812e4fbc45807e8079a3a5b9a.jpg",
    "https://i.pinimg.com/564x/25/67/ce/2567cec38c64ffe7891ba6cc52e15a40.jpg",
    "https://media.tenor.com/images/3a431ae7b90240982d73a2e510a4bcef/tenor.gif",
    "https://media.tenor.com/images/1cb534f664da070ea93504c87ed4a22a/tenor.gif",
    "https://media.tenor.com/images/e54e90e28578603299ffd22367fed567/tenor.gif",
    "https://media.tenor.com/images/cf949eb000cc6a29571d8f33d3988b0e/tenor.gif",
    "https://media.tenor.com/images/e691d48e5becc8327cbf59aa4ddb26b1/tenor.gif",
    "https://i.pinimg.com/236x/97/1c/70/971c7043bbe253252b22bdfaeae0be5b.jpg",
    "https://media.tenor.com/images/c636dc79e409aa4f07317fd8fb59234d/tenor.gif",
    "https://i.pinimg.com/236x/c9/51/f5/c951f5b8a0010c936ecf6a69164a9d74.jpg",
    "https://i.pinimg.com/236x/67/51/17/67511709d519e5de4d62f7f9a76a36b7.jpg",
    "https://i.pinimg.com/236x/db/68/cc/db68cc7ed06c48c70abdc3e9e98e6f10.jpg",
    "https://i.pinimg.com/236x/95/d4/f5/95d4f560373f35cb0c545ab71346c89a.jpg",
    "https://i.pinimg.com/236x/25/42/18/254218364a318bea9074736eb30232ff.jpg",
    "https://i.pinimg.com/236x/9e/79/d9/9e79d93cf10eed6ac8929789205ba35f.jpg",
    "https://i.pinimg.com/236x/ac/a8/80/aca880f0ea3c8f72880629b8e3d928c4.jpg",
    "https://i.pinimg.com/236x/ee/bb/5b/eebb5b6c070e17e28a5845eee06347e5.jpg",
    "https://i.pinimg.com/236x/4f/4e/f8/4f4ef8d6b5524fd90384985b6a0c6a82.jpg",
    "https://i.pinimg.com/236x/59/c6/a9/59c6a93d71e06a14fe1ffec06ad66d47.jpg",
    "https://i.pinimg.com/236x/e7/db/d3/e7dbd3ebc595fc73712a41cdd57c24b3.jpg",
    "https://i.pinimg.com/236x/e1/31/36/e1313603b56f7dfa58d2dff381def06a.jpg",
    "https://i.pinimg.com/236x/62/12/a7/6212a7dc1e349d5450ca4d5f4a24aee2.jpg",
    "https://i.pinimg.com/236x/a0/35/6d/a0356db4b850eac8207bb3c5f2c9ffad.jpg",
    "https://i.pinimg.com/236x/2a/68/3e/2a683e0a6110db40b07e1719bf05a532.jpg",
    "https://i.pinimg.com/236x/75/c1/eb/75c1ebcb985d4c02fe629e966924a7d4.jpg",
    "https://i.pinimg.com/236x/46/36/e3/4636e373a63a91ee887e4ca24f08370b.jpg",
    "https://i.pinimg.com/236x/b5/07/b9/b507b93b5bdd20cc56abacad016087eb.jpg",
    "https://i.pinimg.com/236x/70/4d/95/704d95612396ef77d88599ed81e1cec2.jpg",
    "https://i.pinimg.com/236x/ce/b5/f0/ceb5f0b55a2b870efc4ae2707f1c0125.jpg",
    "https://i.pinimg.com/236x/e3/00/7b/e3007b74b1107f3ae1ec75b9b3bb63d4.jpg",
    "https://i.pinimg.com/236x/5a/f5/e6/5af5e6e224eb408b4e2494f9dd8425e7.jpg",
    "https://i.pinimg.com/236x/f0/86/a0/f086a0a8930b9c24c1978ad33c72dabb.jpg",
    "https://i.pinimg.com/236x/6e/a5/fe/6ea5febbf3628b56a234af354d8bc285.jpg",
    "https://i.pinimg.com/236x/de/ea/45/deea452f264b61fcd9fd6d0dec2f814b.jpg",
    "https://i.pinimg.com/236x/61/bb/38/61bb387ccd0bcb5949a8c46c0f637c68.jpg",
    "https://i.pinimg.com/236x/ee/c7/ed/eec7ede27063eebdc443efcfc7dd9975.jpg",
    "https://i.pinimg.com/564x/78/2e/95/782e95564da9ca39051ff199fea3dfe3.jpg",
    "https://i.pinimg.com/564x/7f/94/65/7f9465fac3a2aa51c6ff435bc8331d0c.jpg",
    "https://i.pinimg.com/564x/dd/67/64/dd67645aa7637d21968f7209de82a5e0.jpg",
    "https://i.pinimg.com/564x/25/cf/31/25cf312b5d50297b4467916806b854ab.jpg",
    "https://i.pinimg.com/564x/38/59/70/385970e57862cb080d5cb7bdef91ca92.jpg",
    "https://i.pinimg.com/564x/3b/92/75/3b9275261fe73376642a4096182f78e0.jpg",
    "https://i.pinimg.com/564x/cb/ec/05/cbec05357defbeeae9f069a458e56999.jpg",
    "https://i.pinimg.com/564x/ca/01/c0/ca01c08334bdf9d255374908ed2e3a93.jpg",
    "https://i.pinimg.com/564x/a1/ca/19/a1ca19919aa1b851a8a7ee696d77f445.jpg",
    "https://i.pinimg.com/564x/0f/be/fa/0fbefa7cedb4ed31a1daf7e6afa74754.jpg",
    "https://i.pinimg.com/564x/46/3a/16/463a1668e5e38a55029d8c2b855b51a1.jpg",
    "https://i.pinimg.com/564x/be/ba/a3/bebaa3ad8a65d320bf2fefdd4db93fab.jpg",
    "https://i.pinimg.com/564x/7d/f0/ed/7df0ed0f4f97001556609f57a0b87b01.jpg",
    "https://i.pinimg.com/564x/8e/24/ef/8e24ef6697bec9164265528bf4e05a8c.jpg",
    "https://i.pinimg.com/564x/5f/93/29/5f9329c62c30b41f525b8995298a0d5c.jpg",
    "https://i.pinimg.com/564x/ae/01/4f/ae014fc32f3687c7c00a6988b5a28e75.jpg",
    "https://i.pinimg.com/564x/44/65/a3/4465a356cf988a8aeca64be611099772.jpg",
    "https://i.pinimg.com/564x/48/4b/2a/484b2ae47442a400771ce7fd589bb07d.jpg",
    "https://i.pinimg.com/564x/9c/47/8d/9c478df0f118988d03951e7dbe6d19fa.jpg",
    "https://i.pinimg.com/564x/c2/d9/32/c2d932ce1cb411a44c156a22aa00ff9f.jpg"
]

countries: list = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Democratic Republic of the Congo",
    "Costa Rica",
    "Côte d'Ivoire",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "North Korea",
    "South Korea",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Türkiye",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Viet Nam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
]

COUNTRIESDIC: dict = {
    "Afghanistan":"af",
    "Albania":"al",
    "Algeria":"dz",
    "Andorra":"ad",
    "Angola":"ao",
    "Antigua and Barbuda":"ag",
    "Argentina":"ar",
    "Armenia":"am",
    "Australia":"au",
    "Austria":"at",
    "Azerbaijan":"az",
    "Bahamas":"bs",
    "Bahrain":"bh",
    "Bangladesh":"bd",
    "Barbados":"bb",
    "Belarus":"by",
    "Belgium":"be",
    "Belize":"bz",
    "Benin":"bj",
    "Bhutan":"bt",
    "Bolivia":"bo",
    "Bosnia and Herzegovina":"ba",
    "Botswana":"bw",
    "Brazil":"br",
    "Brunei Darussalam":"bn",
    "Bulgaria":"bg",
    "Burkina Faso":"bf",
    "Burundi":"bi",
    "Cabo Verde":"cv",
    "Cambodia":"kh",
    "Cameroon":"cm",
    "Canada":"ca",
    "Central African Republic":"cf",
    "Chad":"td",
    "Chile":"cl",
    "China":"cn",
    "Colombia":"co",
    "Comoros":"km",
    "Congo":"cg",
    "Democratic Republic of the Congo":"cd",
    "Costa Rica":"cr",
    "Côte d'Ivoire":"ci",
    "Croatia":"hr",
    "Cuba":"cu",
    "Cyprus":"cy",
    "Czechia":"cz",
    "Denmark":"dk",
    "Djibouti":"dj",
    "Dominica":"dm",
    "Dominican Republic":"do",
    "Ecuador":"ec",
    "Egypt":"eg",
    "El Salvador":"sv",
    "Equatorial Guinea":"gq",
    "Eritrea":"er",
    "Estonia":"ee",
    "Eswatini":"sz",
    "Ethiopia":"et",
    "Fiji":"fj",
    "Finland":"fi",
    "France":"fr",
    "Gabon":"ga",
    "Gambia":"gm",
    "Georgia":"ge",
    "Germany":"de",
    "Ghana":"gh",
    "Greece":"gr",
    "Grenada":"gd",
    "Guatemala":"gt",
    "Guinea":"gn",
    "Guinea-Bissau":"gw",
    "Guyana":"gy",
    "Haiti":"ht",
    "Honduras":"hn",
    "Hungary":"hu",
    "Iceland":"is",
    "India":"in",
    "Indonesia":"id",
    "Iran":"ir",
    "Iraq":"iq",
    "Ireland":"ie",
    "Israel":"il",
    "Italy":"it",
    "Jamaica":"jm",
    "Japan":"jp",
    "Jordan":"jo",
    "Kazakhstan":"kz",
    "Kenya":"ke",
    "Kiribati":"ki",
    "North Korea":"kp",
    "South Korea":"kr",
    "Kuwait":"kw",
    "Kyrgyzstan":"kg",
    "Laos":"la",
    "Latvia":"lv",
    "Lebanon":"lb",
    "Lesotho":"ls",
    "Liberia":"lr",
    "Libya":"ly",
    "Liechtenstein":"li",
    "Lithuania":"lt",
    "Luxembourg":"lu",
    "Madagascar":"mg",
    "Malawi":"mw",
    "Malaysia":"my",
    "Maldives":"mv",
    "Mali":"ml",
    "Malta":"mt",
    "Marshall Islands":"mh",
    "Mauritania":"mr",
    "Mauritius":"mu",
    "Mexico":"mx",
    "Micronesia":"fm",
    "Moldova":"md",
    "Monaco":"mc",
    "Mongolia":"mn",
    "Montenegro":"me",
    "Morocco":"ma",
    "Mozambique":"mz",
    "Myanmar":"mm",
    "Namibia":"na",
    "Nauru":"nr",
    "Nepal":"np",
    "Netherlands":"nl",
    "New Zealand":"nz",
    "Nicaragua":"ni",
    "Niger":"ne",
    "Nigeria":"ng",
    "North Macedonia":"mk",
    "Norway":"no",
    "Oman":"om",
    "Pakistan":"pk",
    "Palau":"pw",
    "Panama":"pa",
    "Papua New Guinea":"pg",
    "Paraguay":"py",
    "Peru":"pe",
    "Philippines":"ph",
    "Poland":"pl",
    "Portugal":"pt",
    "Qatar":"qa",
    "Romania":"ro",
    "Russia":"ru",
    "Rwanda":"rw",
    "Saint Kitts and Nevis":"kn",
    "Saint Lucia":"lc",
    "Saint Vincent and the Grenadines":"vc",
    "Samoa":"ws",
    "San Marino":"sm",
    "Sao Tome and Principe":"st",
    "Saudi Arabia":"sa",
    "Senegal":"sn",
    "Serbia":"rs",
    "Seychelles":"sc",
    "Sierra Leone":"sl",
    "Singapore":"sg",
    "Slovakia":"sk",
    "Slovenia":"si",
    "Solomon Islands":"sb",
    "Somalia":"so",
    "South Africa":"za",
    "South Sudan":"ss",
    "Spain":"es",
    "Sri Lanka":"lk",
    "Sudan":"sd",
    "Suriname":"sr",
    "Sweden":"se",
    "Switzerland":"ch",
    "Syria":"sy",
    "Tajikistan":"tj",
    "Tanzania":"tz",
    "Thailand":"th",
    "Timor-Leste":"tl",
    "Togo":"tg",
    "Tonga":"to",
    "Trinidad and Tobago":"tt",
    "Tunisia":"tn",
    "Türkiye":"tr",
    "Turkmenistan":"tm",
    "Tuvalu":"tv",
    "Uganda":"ug",
    "Ukraine":"ua",
    "United Arab Emirates":"ae",
    "United Kingdom":"gb",
    "United States":"us",
    "Uruguay":"uy",
    "Uzbekistan":"uz",
    "Vanuatu":"vu",
    "Venezuela":"ve",
    "Viet Nam":"vn",
    "Yemen":"ye",
    "Zambia":"zm",
    "Zimbabwe":"zw"
}